name: 'job_agg_pipeline'
version: '1.0'
config-version: 2

profile: 'job_agg_profile'

model-paths: ['dbt_project/models']
seed-paths: ['dbt_project/seeds']
test-paths: ['dbt_project/tests']
macro-paths: ['dbt_project/macros']
snapshot-paths: ['dbt_project/snapshots']

analysis-paths: ['dbt_project/analysis']
docs-paths: ['dbt_project']

target-path: 'logs'
clean-targets: ['logs', 'dbt_packages']

models:
  job_agg_pipeline:
    staging:
      +materialized: view
    gold:
      +materialized: table
