name: 'job_agg_dbt'
version: '1.0.0'
config-version: 2

profile: 'job_agg_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  silver_path: "C:/Users/sharm/job-agg-pipeline/data/silver/silver.parquet"

models:
  job_agg_dbt:
    staging:
      +materialized: view
    gold:
      +materialized: table